### ISSUE TITLE
The form title does not support Unicode characters such as Chinese / Japanese

### ISSUE THREAD

**Issue by limocute** [AlzPatz/yak2d#2]
Hello, I found that the title of the form does not support Chinese / Japanese and other Unicode characters when using yak2d. What should I do?

**Comment by AlzPatz** [comment]
Hi!

Are you experiencing this problem with Yak2D only or also with Veldrid?

I do not believe the issue here lies with Yak2D as it simply passes a string to the change window title method of Veldrid. 

It seems as if SDL2 does not handle Unicode characters well in the window title (and that results can be platform specific). Therefore there may not be a perfect solution.

However, it does appear as though some have had success when using SDL in C++ to mitigate this issue by passing a UTF-8 string to SDL_SetWindowTitle()

It may be the case that a simple change or cast could be applied to the string that Veldrid passes to the Native SDL call.

I will take a look and see if there is a fix I can put in a pull request in Veldrid. It might help. Failing that I am not sure if there is a solution I can suggest.

**Comment by limocute** [comment]
Hi， It seems that someone has done this work ([UTF-8 Marshaling](https://github.com/flibitijibibo/SDL2-CS/pull/22)). I will try it when I have free time

**Comment by AlzPatz** [comment]
Nice find - keep me posted!

**Comment by limocute** [comment]
The problem has been solved. I will submit PR to veldrid later
