### ISSUE TITLE
Is there an API similar to the pushaxisalignedclip method in direct2d

### ISSUE THREAD

**Issue by limocute** [AlzPatz/yak2d#3]
Hello, does yak2d have an API similar to the [pushaxisalignedclip](https://docs.microsoft.com/zh-cn/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-pushaxisalignedclip(constd2d1_rect_f__d2d1_antialias_mode)?redirectedfrom=MSDN) and [popaxisalignedclip](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-popaxisalignedclip) methods in direct2d.

When I draw the UI in a game, I need to specify a rectangular area when I draw the image on the screen, so that the image that is finally drawn on the screen is the content of the rectangular area.

Direct2d is used as follows
```
void draw()
{
 //The image drawn using drawbitmap between the pushaxisalignedclip and popaxisalignedclip methods will crop the image content outside the rectangular area
  D2D1DeviceContext.PushAxisAlignedClip(clipRect, antialiasMode);
  D2D1DeviceContext.DrawBitmap(...);
  D2D1DeviceContext.DrawBitmap(...);
  D2D1DeviceContext.PopAxisAlignedClip();
}
```

**Comment by AlzPatz** [comment]
Hello - yes there is. You must use a viewport.

A viewport defines the area to draw within a render target. It is defined in terms of pixels

You create a viewport doing the following, normally within CreateResources():

```
_myviewport = yak.Stages.CreateViewport(x, y, width, height);

```

Where:
x = top left corner of the viewport pixel x position on render target
y = top left corner of the viewport pixel y position on render target
width = pixel width of viewport
height = pixel height of viewport

The 'coordinate system' used for viewports is defined as the top left corner of a rendertarget surface is pixel (0,0), and the bottom right is of course (width - 1, height - 1).

If I had a rendertarget surface which was 800x600 pixels and I wanted a viewport that allowed me to render to a 400x600 area on the right hand side of the surface, I would create

```
_myviewport = yak.Stages.CreateViewport(400, 0, 400, 600);
```


Using a viewport.

When you are building your render queue, first set your viewport object as the active one.

Then any rendering (queued render stages) you do after this will render everything to the defined area of whichever render target surface is chosen.

To remove the viewport you call the appropriate method, and any subsequent rendering calls target the entire render surface.

the below example small render queue creation method sets a viewport, draws the polys of a draw stage (sprites and other coloured or textured draw requests) to a portion of the screen. The viewport is then cleared and the next UI draw stage render then targets the entire render target surface which happens to be the window frame buffer in this case:

```
 public override void Rendering(IRenderQueue q, IRenderTarget windowRenderTarget)
        {
            q.ClearColour(windowRenderTarget, Colour.Clear);
            q.ClearDepth(windowRenderTarget);

            q.SetViewport(_myviewport);
            q.Draw(_drawStageGame, _cameraGame, windowRenderTarget);

            q.RemoveViewport();
            q.Draw(_drawStageGui, _cameraGui, windowRenderTarget);
        }
```

Important to note.

Drawing and Rendering operations in Yak2D are rendertarget surface size agnostic. What this means is that a draw or render stage operation will fill the entire defined viewport area (or entire rendertarget if no viewport is defined).

What this means in practice is that if you are Drawing sprites using a draw stage, the 'size' of the rendered area in the game world is defined by the camera object and its dimensions (it's virtual resolution).

You must therefore set up an appropriate camera for the aspect ration of the render area.

So, if you have a window of 800 x 600 size, and you have been using a camera2D to render a drawstage to the full size of the render target, and you want to just render to half of the screen, to avoid squashing the 800 x 600 projection into a 400x 600 space you should use a new camera2D object that is set up to render into 400 x 600 (OR just the correct aspect ratio).

There is no requirement that the camera world 'virtual' resolution be the same as the target area, but if they do not have the same aspect ratio you will get distortion in what you try and render.

I hope that makes sense. The reason it is like this, is if you pick say 16:9 aspect ratio and assume to use virtual resolutions in the camera of 1920x1080. You could change the actual screen resolution (window rendertarget size in pixels) to say 2560x1440 or 4K and the game would render at the higher resolution fine, without any distortion.

In the samples repo, viewports are used in "Draw_SplitScreenExample"

If you clone that repo now, it is referencing a local copy of Yak2D. you can simply change SampleBase.csproj to reference the pacakge rather than the hard include (uncomment the following):

````
<!--
  <ItemGroup>
    <PackageReference Include="Yak2D" Version="0.0.5" />
  </ItemGroup>
-->
````

and comment out or delete:

```
  <ItemGroup>
    <ProjectReference Include="..\..\..\yak2d\src\Yak2D\Yak2D.csproj" />
  </ItemGroup>
```

There are many examples in the samples projects that show how to use various parts of Yak2D.

I am also currently working on the docs and should have some detailed instructions for use some time in early Q1 2021 :) perhaps I can get something done sooner over the holiday season

Let me know if you have any other questions

**Comment by limocute** [comment]
Thank you for your answer. I already know what to do

**Comment by limocute** [comment]
Excuse me, how to adjust the position of Viewport at any time in the rendering cycle？
My scene is as follows: draw the backpack interface of game characters in the viewport (the drawing of items in the backpack will be limited in the viewport area). This backpack interface can be dragged by the mouse。
Maybe I shouldn't use a Viewport for a scene like mine

**Comment by AlzPatz** [comment]
You would need to create a new viewport if it’s position and size changes. I would suggest doing this in PreDrawing() which is called once before the drawing and rendering methods, but has access to Stages and viewport creation. Viewports are very lightweight objects so I don’t think you’ll run into any issues creating and destroying them every frame. I’d advise that you do destroy old viewports rather than dropping reference to them, as they’ll sit in a viewport collection until the end of the application.

you have many other options to achieve the same effect, but I’m sure a new viewport each frame is fine.

FYI - you might have inferred this already but the objects you get passed by the framework for different items (textures, viewports, renderstages etc) are all simply wrappers of int64 ids. The framework manages the collection of actual objects in the background. This is why you need to destroy items explicitly.

let me know if you have any other questions!

**Comment by limocute** [comment]
Thank you for your answer, I have achieved the function I want
